# Auto-CoT Prompting Example

# Import load_dotenv to load environment variables from a .env file
from dotenv import load_dotenv

# Import the OpenAI client
from openai import OpenAI

# Import os to read environment variables
import os

# Load environment variables from the .env file (e.g., OPENAI_API_KEY)
load_dotenv()

# Create an OpenAI client using the API key stored in the environment
client = OpenAI(api_key=os.getenv("OPENAI_API_KEY"))

# --------------------------------------
# STEP 1: Ask the model to generate its own example + reasoning
# --------------------------------------

# Call the OpenAI chat completion API to generate an example with reasoning
example_response = client.chat.completions.create(
    model="gpt-4o-mini",  # Use a small, fast model
    messages=[
        {
            # System message: tells the model what kind of response we want
            "role": "system",
            "content": "Create ONE example of solving a simple arithmetic expression with step-by-step reasoning."
        },
        {
            # User message: asks for a single example, but tells it NOT to solve our real target expression yet
            "role": "user",
            "content": "Give one example and solve it step by step. Do NOT solve 2 + 3 * 4 yet."
        }
    ]
)

# Extract the example text generated by the model
auto_example = example_response.choices[0].message.content

# Print the auto-generated example so we can see the style of reasoning
print("🔹 Auto-generated example (for style):")
print(auto_example)
print("\n" + "-"*50 + "\n")  # Print a separator line for readability

# --------------------------------------
# STEP 2: Use that auto-generated example as a pattern for the real question
# --------------------------------------

# Call the API again, this time using the previous example as a demonstration
final_response = client.chat.completions.create(
    model="gpt-4o-mini",  # Same model as before
    messages=[
        {
            # System message: provide the auto-generated example and instruct the model
            "role": "system",
            "content": (
                "Here is an example of how to solve a math problem step-by-step:\n\n"
                f"{auto_example}\n\n"
                "Now solve the next problem using the SAME step-by-step style."
            )
        },
        {
            # User message: this is the real math problem we want solved
            "role": "user",
            "content": "Solve 2 + 3 * 4"
        }
    ]
)

# Print the final answer that follows the style of the auto-generated example
print("🤖 Final Answer with Auto-CoT style:")
print(final_response.choices[0].message.content)
